# Generated by Django 2.0.13 on 2020-04-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiesgoEvaluacioncualitativaresidualupdate',
            fields=[
                ('idriesgo', models.CharField(blank=True, db_column='IdRiesgo', max_length=255, null=True)),
                ('idecr', models.CharField(blank=True, db_column='IdECR', max_length=255, null=True)),
                ('probabilidadresidual', models.FloatField(blank=True, db_column='ProbabilidadResidual', null=True)),
                ('impactoresidual', models.FloatField(blank=True, db_column='ImpactoResidual', null=True)),
                ('impactocapexresidual', models.FloatField(blank=True, db_column='ImpactoCapexResidual', null=True)),
                ('impactoplazoresidual', models.FloatField(blank=True, db_column='ImpactoPlazoResidual', null=True)),
                ('impactoeconomicoresidual', models.FloatField(blank=True, db_column='ImpactoEconomicoResidual', null=True)),
                ('impactossoresidual', models.FloatField(blank=True, db_column='ImpactoSSOResidual', null=True)),
                ('impactomedioambienteresidual', models.FloatField(blank=True, db_column='ImpactoMedioambienteResidual', null=True)),
                ('impactocomunitarioresidual', models.FloatField(blank=True, db_column='ImpactoComunitarioResidual', null=True)),
                ('impactoreputacionalresidual', models.FloatField(blank=True, db_column='ImpactoReputacionalResidual', null=True)),
                ('impactolegalresidual', models.FloatField(blank=True, db_column='ImpactoLegalResidual', null=True)),
                ('ambitodominanteresidual', models.FloatField(blank=True, db_column='AmbitoDominanteResidual', null=True)),
                ('magnitudriesgoresidual', models.FloatField(blank=True, db_column='MagnitudRiesgoResidual', null=True)),
                ('nivelriesgoresidual', models.CharField(blank=True, db_column='NivelRiesgoResidual', max_length=255, null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
                ('modificado', models.DateTimeField(blank=True, db_column='Modificado', null=True)),
                ('creado', models.DateTimeField(db_column='Creado', primary_key=True, serialize=False)),
                ('creadopor', models.CharField(blank=True, db_column='Creadopor', max_length=255, null=True)),
                ('modificadopor', models.CharField(blank=True, db_column='Modificadopor', max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'RIESGO_EvaluacionCualitativaResidualUpdate',
            },
        ),
        migrations.CreateModel(
            name='RiesgoMagnitudnivel',
            fields=[
                ('probabilidad', models.IntegerField(blank=True, db_column='Probabilidad', null=True)),
                ('impacto', models.IntegerField(blank=True, db_column='Impacto', null=True)),
                ('magnitud', models.IntegerField(blank=True, db_column='Magnitud', null=True)),
                ('nivel', models.CharField(blank=True, db_column='Nivel', max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'RIESGO_MagnitudNivel',
            },
        ),
        migrations.CreateModel(
            name='RiesgoProbImp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.IntegerField(blank=True, db_column='Probabilidad', null=True)),
                ('impacto', models.IntegerField(blank=True, db_column='Impacto', null=True)),
                ('color_hex', models.CharField(blank=True, db_column='Color_hex', max_length=255, null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'RIESGO_PROB_IMP',
            },
        ),
        migrations.CreateModel(
            name='RiesgoUnifica',
            fields=[
                ('idregistro', models.CharField(db_column='IdRegistro', max_length=100, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=100, null=True)),
                ('superintendencia', models.CharField(blank=True, db_column='SuperIntendencia', max_length=100, null=True)),
                ('unidadoperacional', models.CharField(blank=True, db_column='UnidadOperacional', max_length=100, null=True)),
                ('area', models.CharField(blank=True, db_column='Area', max_length=255, null=True)),
                ('sector', models.CharField(blank=True, db_column='Sector', max_length=255, null=True)),
                ('lugar', models.CharField(blank=True, db_column='Lugar', max_length=255, null=True)),
                ('tipoobjeto', models.CharField(blank=True, db_column='TipoObjeto', max_length=100, null=True)),
                ('evento', models.CharField(blank=True, db_column='Evento', max_length=200, null=True)),
                ('nivelimpacto', models.CharField(blank=True, db_column='NivelImpacto', max_length=200, null=True)),
                ('comentarios', models.CharField(blank=True, db_column='Comentarios', max_length=500, null=True)),
                ('qhorasdetencion', models.CharField(blank=True, db_column='QHorasDetencion', max_length=500, null=True)),
                ('qdiasdetencion', models.CharField(blank=True, db_column='QDiasDetencion', max_length=500, null=True)),
                ('qktsperdida', models.CharField(blank=True, db_column='QKtsPerdida', max_length=500, null=True)),
                ('qtmfperdida', models.CharField(blank=True, db_column='QTMFperdida', max_length=500, null=True)),
                ('qlibrasperdida', models.CharField(blank=True, db_column='QLibrasPerdida', max_length=500, null=True)),
                ('montoperdidakusd', models.CharField(blank=True, db_column='MontoPerdidaKUSD', max_length=500, null=True)),
                ('idriesgoasociado', models.CharField(blank=True, db_column='IdRiesgoAsociado', max_length=50, null=True)),
                ('familia', models.CharField(blank=True, db_column='Familia', max_length=255, null=True)),
                ('subproceso', models.CharField(blank=True, db_column='SubProceso', max_length=255, null=True)),
                ('clasificacion', models.CharField(blank=True, db_column='Clasificacion', max_length=255, null=True)),
                ('tipofalla', models.CharField(blank=True, db_column='TipoFalla', max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'RIESGO_UNIFICA',
            },
        ),
    ]
